services:
  - type: web
    name: hospital-management
    runtime: docker
    repo: https://github.com/ablas123/Hospital-Management-System-Project
    plan: free
    envVars:
      - key: DATABASE_HOST
        value: sql200.infinityfree.com
      - key: DATABASE_USER
        value: if0_41411754
      - key: DATABASE_PASSWORD
        value: ablasmoh
      - key: DATABASE_NAME
        value: if0_41411754_ablas
