services:
  - type: web
    name: hospital-management
    runtime: docker
    repo: https://github.com/ablas123/Hospital-Management-System-Project
    plan: free
    envVars:
      - key: DATABASE_URL
        value: mysql://if0_41411754:ablasmoh@sql200.infinityfree.com:3306/if0_41411754_ablas
